version: 2.1

# orbs:
#   contrastsecurity: contrastsecurity/verify@0.3.0

jobs:
  hello-job:
    docker:
      # - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
      - image: node:18
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: install-dependencies 
          command: npm install 
      - run: 
          name: install-contrast 
          command: npm install @contrast/agent@4.37
      - run: 
          name: run contrast
          command: npm run contrast

workflows:
  my-workflow:
    jobs:
      - hello-job