version: 2.1

# orbs:
#   contrastsecurity: contrastsecurity/verify@0.3.0

jobs:
  hello-job:
    docker:
      # - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
      - image: node:18
    steps:
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
          name: git config
          command: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - checkout # check out the code in the project directory
      - run:
          name: npm config
          command: npm config set registry https://registry.npmjs.org/ |
                  npm config set strict-ssl false
      - run: 
          name: install-dependencies 
          command: npm install --verbose
      - run: 
          name: install-contrast 
          command: npm install @contrast/agent@4.37
      - run: 
          name: run contrast
          command: npm run contrast

workflows:
  my-workflow:
    jobs:
      - hello-job