version: 2.1

orbs:
  contrastsecurity: contrastsecurity/verify@0.3.0

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: install-dependencies 
          command: npm install 
      - run: 
          name: tests
          command: npm test
      - contrastsecurity/check-vulnerabilities:
        application-id: helloworldcircleci
        contrast-url: https://app.contrastsecurity.com/Contrast
        # org-id: 
        # severities: 

workflows:
  my-workflow:
    jobs:
      - hello-job