version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: 
          name: install-dependencies 
          command: npm install 
      - run: 
          name: tests
          command: npm test

workflows:
  my-workflow:
    jobs:
      - hello-job