version: 2.1

orbs:
  contrastsecurity: contrastsecurity/verify@0.3.0

jobs:
  hello-job:
    docker:
      # - image: cimg/node:17.2.0 # the primary container, where your job's commands are run
      - image: node18zscaler
    # working_directory: ~/work
    steps:
      # - run:
      #     name: Install Docker Compose
      #     environment:
      #       COMPOSE_VERSION: '1.29.2'
      #     command: |
      #       curl -kL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
      #       chmod +x ~/docker-compose
      #       mv ~/docker-compose /usr/local/bin/docker-compose
      # - run:
      #     name: Start container and verify it's working
      #     command: |
      #       set -x
      #       docker-compose up -d

      #       # docker-compose will start 2 containers, the one with service will be named `contacts`
      #       # we start another container with curl in the same network as `contacts`, this way we have
      #       # all exposed ports from `contacts` available on `localhost` in this new container
      #       docker run --network container:contacts \
      #         appropriate/curl --retry 10 --retry-delay 1 --retry-connrefused http://localhost:8080/contacts/test
      - run:
          name: git config
          command: git config --global --add safe.directory /tmp/_circleci_local_build_repo
      - run:
          name: mkdir
          command: |
              mkdir -p /tmp/_circleci_local_build_repo
              cd /tmp/_circleci_local_build_repo
              git init
      - checkout # check out the code in the project directory
      # - run:
      #     name: Hello World
      #     command: echo "hello world"
      - run:
          name: npm config
          command: npm config set registry https://registry.npmjs.org/ |
                  npm config set strict-ssl false
      - run:
          name: update-ca-certificates
          command: update-ca-certificates --fresh
      - run: 
          name: install-dependencies 
          command: npm install --verbose
      - run: 
          name: install-contrast 
          command: npm install @contrast/agent@4.37
      - run:
          name: install-pip
          command: apt update
      - run:
          name: install-pip
          command: apt upgrade -y
      - run:
          name: install-pip
          command: apt install python3-pip
      # - run:
      #     name: npm audit
      #     command: npm audit
      # - run:
      #     name: npm audit fix
      #     command: npm audit fix
      - contrastsecurity/check-vulnerabilities:
          application-id: circlecihelloworld
          contrast-url: https://app.contrastsecurity.com/Contrast
          org-id: "516A7010-26A7-4C03-B363-0AF8FDCEBAD4"
          severities: CRITICAL,HIGH,MEDIUM
      - run: 
          name: run contrast
          command: npm run contrast

workflows:
  my-workflow:
    jobs:
      - hello-job